// Data for procedurally generating game maps

#ifndef _MAPGEN_DATA_H_
#define _MAPGEN_DATA_H_

#include <stdint.h>

#define BIOME_COUNT 64
#define BIOME_CONNECTION_COUNT 32
#define COLUMNS_PER_BIOME 20
#define MINIMUM_CAVE_WIDTH 4
#define WIDE_OPEN_BIOMES_START 50

// Data for biome columns
//
// Format: 20 columns for each biome. Each column consists of two 4-bit numbers stored in a uint8_t:
//   * Higher 4 bits: The starting row of the cave
//   * Lower 4 bits: The width of the cave, minus the MINIMUM_CAVE_WIDTH
//
// Note that these biomes were generated by the `tools/generate_biome.go` program. See that file
// for more info about the different types of biomes that were generated.
extern const uint8_t biome_columns[BIOME_COUNT][COLUMNS_PER_BIOME];

// Which biomes can be used after the current biome.
// Note that this data was generated by the `tools/generate_biome.go` program.
extern const uint8_t next_possible_biomes[BIOME_COUNT][BIOME_CONNECTION_COUNT];

#endif
